# Generated by Django 6.1.1 on 2026-09-28 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=180)),
                ('principio_activo', models.CharField(blank=True, max_length=180)),
                ('lote', models.CharField(max_length=60)),
                ('fecha_vencimiento', models.DateField()),
                ('categoria', models.CharField(choices=[('QUIRURGICO', 'Material Quirurgico'), ('MEDICAMENTO', 'Medicamentos & Farmacos'), ('EQUIPAMIENTO', 'Equipamiento Clinico')], default='MEDICAMENTO', max_length=20)),
                ('precio_caja', models.DecimalField(decimal_places=0, max_digits=12)),
                ('stock_cajas', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro_activo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.carro')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.insumo')),
            ],
            options={
                'unique_together': {('carro', 'insumo')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudAbastecimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Validacion'), ('PAGADO', 'Pagado y Autorizado'), ('ENTREGADO', 'Entregado en Clinica'), ('CANCELADO', 'Cancelado / Quiebre Frio')], default='PENDIENTE', max_length=20)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_historico', models.CharField(max_length=180)),
                ('lote_historico', models.CharField(max_length=60)),
                ('precio_unitario_historico', models.DecimalField(decimal_places=0, max_digits=12)),
                ('cantidad', models.PositiveIntegerField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.insumo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='store.solicitudabastecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('INSTITUCION_MEDICA', 'Institucion Medica (Cliente)'), ('GESTOR_BODEGA', 'Gestor de Bodega Farmaceutica (Admin)')], default='INSTITUCION_MEDICA', max_length=30)),
                ('institucion_nombre', models.CharField(blank=True, default='', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
