# Generated by Django 6.1.1 on 2026-09-28 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_insumo_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitudabastecimiento',
            name='total',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('INSTITUCION_MEDICA', 'Institucion Medica / Comprador'), ('GESTOR_BODEGA', 'Gestor de Bodega Farmaceutica')], default='INSTITUCION_MEDICA', max_length=30),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='store.categoriainsumo'),
        ),
    ]
