# Generated by Django 6.1.1 on 2026-09-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_categoriainsumo_remove_solicitudabastecimiento_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudabastecimiento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Validación'), ('PAGADO', 'Pagado y Autorizado'), ('ENTREGADO', 'Entregado en Clínica'), ('CANCELADO', 'Cancelado / Quiebre Frío')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('INSTITUCION_MEDICA', 'Institución Médica / Comprador'), ('GESTOR_BODEGA', 'Gestor de Bodega (Admin)')], default='INSTITUCION_MEDICA', max_length=30),
        ),
    ]
